### ISSUE TITLE
Timeout 403 unable to request

### ISSUE THREAD

**Issue by imloualvaro** [ikhsanalatsary/MeowTube#16]
`meowtube play video "videoIDhere" -r 1080p
Request video...
Get "https://uptime.invidious.io/api/getMonitorList/89VnzSKAn?page=1&_=1611588676444": dial tcp: lookup uptime.invidious.io on 192.168.1.1:53: read udp 192.168.1.30:55250->192.168.1.1:53: i/o timeout`

running latest version. until last night was working fine.

**Comment by ikhsanalatsary** [comment]
it's working now. I think there was a down time

**Comment by imloualvaro** [comment]
still same thing
