### ISSUE TITLE
invidious down

### ISSUE THREAD

**Issue by 89z** [ikhsanalatsary/MeowTube#17]
From this code:

https://github.com/ikhsanalatsary/MeowTube/blob/179f9c08ce6f411974a8518fad0e4dfa0809d7db/instances/data.go#L132-L133

I tried this:

~~~
GET /api/getMonitorList/89VnzSKAn?page=1&_=1611588676444 HTTP/2
Host: uptime.invidious.io
~~~

which results in a redirect, so I make another request:

~~~
GET /89VnzSKAn/api/getMonitorList/89VnzSKAn?page=1&_=1611588676444 HTTP/2
Host: stats.uptimerobot.com
~~~

which results with this:

~~~
HTTP/2.0 404 Not Found
Date: Tue, 24 Aug 2021 22:12:34 GMT
Status: 404 Not Found
~~~

**Comment by ikhsanalatsary** [comment]
A new problem appears #19 😄
